#!/bin/python3
import requests
from sys import argv
from os import path
from os import system

_HELP_ = "usage: i3autowall [monitors] <keyword>"
categories =[
                {
                    'label': "All",
                    'value': '1065976'
                },
                {
                    'label': "1080p",
                    'value': '1339107'
                },
                {
                    'label':  "4K",
                    'value': '1339090'
                },
                {
                    'label':  "Ultra Wide",
                    'value': '1339089'
                },
                {
                    'label':  "Background",
                    'value': '1339276'
                },
                {
                    'label':  "Lock Screen",
                    'value': '1339070'
                },
                {
                    'label':  "Nature",
                    'value': '1065376'
                },
                {
                    'label':  "Tumblr",
                    'value': '1111644'
                },
                {
                    'label':  "Black",
                    'value': '1101680'
                },
                {
                    'label':  "Flower",
                    'value': '1100232'
                },
                {
                    'label':  "Funny",
                    'value': '1111682'
                },
                {
                    'label':  "Cute",
                    'value': '1111680'
                },
                {
                    'label':  "Cool",
                    'value': '1111678'
                },
                {
                    'label':  "Fall",
                    'value': '1100229'
                },
                {
                    'label':  "Love",
                    'value': '1066280'
                },
                {
                    'label':  "Design",
                    'value': '1066276'
                },
                {
                    'label':  "Christmas",
                    'value': '1066273'
                },
                {
                    'label':  "Travel",
                    'value': '1065428'
                },
                {
                    'label':  "Beach",
                    'value': '1065423'
                },
                {
                    'label':  "Car",
                    'value': '1065408'
                },
                {
                    'label':  "Sports",
                    'value': '1065402'
                },
                {
                    'label':  "Animal",
                    'value': '1065390'
                },
                {
                    'label':  "People",
                    'value': '1065386'
                },
                {
                    'label':  "Music",
                    'value': '1065384'
                },
                {
                    'label':  "Summer",
                    'value': '1065380'
                },
                {
                    'label':  "Galaxy",
                    'value': '1065374'
                }
            ]
def main():
    if len(argv) == 2:
        monitors= 1
        keyword = argv[1]
    elif len(argv) == 3:
        monitors = int(argv[1])
        keyword = argv[2]
    else:
        print(_HELP_)
        exit(0)

    collectionId='1065976'
    for elem in categories:
        if keyword == elem['label']:
            collectionId=elem['value'] 
    url= f'https://source.unsplash.com/collection/{collectionId}/1920x1080/daily' 
    img_data = requests.get(url).content
    with open(path.expanduser("~/.i3autowall/paper"), 'wb') as handler:
        handler.write(img_data)

    base= f" --bg-scale {path.expanduser('~/.i3autowall/paper')}"
    paths = base
    if monitors > 1:
        for i in range(0,monitors):
           paths += base
    system(f'feh {paths}')

if __name__ == "__main__":
    main()
